declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_BASE_OAUTH_STATE: string;
    NEXT_PUBLIC_API_BASE_URL: string;
    NEXT_PUBLIC_STATE_ID_COOKIE_LIFETIME: number;
    NEXT_PUBLIC_GOOGLE_BASE_URL: string;
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: string;
    NEXT_PUBLIC_GOOGLE_STATE: string;
    NEXT_PUBLIC_FACEBOOK_APP_ID: string;
    NEXT_PUBLIC_FACEBOOK_STATE: string;
    NEXT_PUBLIC_CLOUDINARY_API_BASE_URL: string;
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: string;
    NEXT_PUBLIC_CLOUDINARY_API_KEY: string;
    NEXT_PUBLIC_CLOUDINARY_API_SECRET: string;
    NEXT_PUBLIC_GOOGLE_REDIRECT_URI: string;
  }
}
